/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "FreeRTOS.h"
#include "task.h"
#include "FreeRTOSConfig.h"
#include "led.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vLedTask1(void *pvParam)

{
	while(1)
	{
		led_toggle1(2);
		vTaskDelay(1000);
	}
	vTaskDelete(NULL);
}
void vLedTask2(void *pvParam)
{

	while(1)
	{

				led_toggle2(2);
		         vTaskDelay(3000);

	}
	vTaskDelete(NULL);
}
void vLedTask3(void *pvParam)
{

	while(1)
	{

				led_toggle3(2);
				vTaskDelay(5000);

	}
	vTaskDelete(NULL);
}
void vLedTask4(void *pvParam)
{
	while(1)
	{
			led_toggle4(2);
			vTaskDelay(7000);
		}
	vTaskDelete(NULL);
}


int main(void)
{
	BaseType_t ret;
	led_init();

	{

	ret = xTaskCreate(vLedTask1, "LED Toggle", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

	}
	ret = xTaskCreate(vLedTask2, "LED Toggle", configMINIMAL_STACK_SIZE, NULL, 2, NULL);
	ret = xTaskCreate(vLedTask3, "LED Toggle", configMINIMAL_STACK_SIZE, NULL, 3, NULL);
	ret = xTaskCreate(vLedTask4, "LED Toggle", configMINIMAL_STACK_SIZE, NULL, 4, NULL);

	if(ret != pdTRUE)
		while(1);

	vTaskStartScheduler();
	while(1);
	return 0;
}







